.\ComfyUI\custom_nodes\ComfyUI-Trellis2
.\ComfyUI\models\facebook
.\ComfyUI\models\microsoft\TRELLIS.2-4B
.\ComfyUI\user\default\workflows\(基础模型)微软Trellis2工作流Advanced.json

#文件总共16.7g,whl文件一个一个拖拽安装,安装flex_gemm-0.0.1-cp311-cp311-win_amd64.whl要打开梯子
#可能会用到TRELLIS2的模型地址https://huggingface.co/microsoft/TRELLIS-image-large/tree/main
#开源地址https://github.com/visualbruno/ComfyUI-Trellis2
#演示https://www.bilibili.com/video/BV1yPqzBCEdn/?share_source=copy_web&vd_source=0a25370d4b68745445397613e7d3fb6e